frequency: 0.2
nodes: [
/base/laser,
/base/laser/laser_filter,
/base/neo_kinematics_differential_node,
/base/relayboard_v2/relayboard_v2_node,
/base/us_avoid_collision,
/base/velocity_smoother,
/cam_back/realsense2_camera_manager,
/cam_back/republish_rgbd_sync_velo_back_rgb,
/cam_back/rgbd_sync_back,
/cam_back/rgbd_sync_velo_back,
/cam_back/rotate_image_depth,
/cam_back/rotate_image_rgb,
/cam_front/realsense2_camera_manager,
/cam_front/republish_rgbd_sync_velo_front_rgb,
/cam_front/rgbd_sync_front,
/cam_front/rgbd_sync_velo_front,
/ekf,
/pcl_repub_velo,
/pointcloud_to_laserscan_node,
/robot_state_publisher,
/velodyne_nodelet_manager,
/velodyne_nodelet_manager_driver,
/velodyne_nodelet_manager_transform,
/xsens_driver
]

monitoring:
    frequency: 0.2 
monitor_mode : 2
#AggregationStrategies mode: 1 LAST, 2 FIRST, 3 MIN, 4 MAX, 5 AVG#
