frequency: 1
topics: [{name: /monitoring, frequency: 2},
         {name: /base/laser/scan_filtered, frequency: 2},
         {name: /base/relayboard_v2/battery_state, frequency: 2},
         {name: /base/relayboard_v2/emergency_stop_state, frequency: 2},
         {name: /base/relayboard_v2/state, frequency: 2},
         {name: /base/relayboard_v2/usboard/measurements, frequency: 2},
         {name: /cam_back/color/camera_info, frequency: 2},
         {name: /cam_front/color/camera_info, frequency: 2},
         {name: /cmd_vel_safe, frequency: 2},
         {name: /cmd_vel_us, frequency: 2},
         {name: /diagnostics, frequency: 2},
         {name: /imu/data, frequency: 2},
         {name: /odom, frequency: 2},
         {name: /odometry/filtered, frequency: 2},
         {name: /velodyne_laserscan, frequency: 2},

]
