monitoring:
  frequency: 0.1   #Publish and calculation frequency
percent: true   #RAM load in %
used: true      #RAM load in KB

monitor_mode : 2
#AggregationStrategies mode: 1 LAST, 2 FIRST, 3 MIN, 4 MAX, 5 AVG#
